<?php
require_once "../clases/conexion.php";
require_once "../clases/metodos.php";
$obj = new crud();

$datos = array(
$_REQUEST['anio'],
$_REQUEST['txtNombresCompletos'],
$_REQUEST['txtPrimerApellido'],
$_REQUEST['txtSegundoApellido'],
$_REQUEST['txtGrado'],
$_REQUEST['txtSexo'],
$_REQUEST['txtTipoDoc'],
$_REQUEST['NoDocumento'],
$_REQUEST['txtLugarNacimiento'],
$_REQUEST['txtFechaNacimiento'],
$_REQUEST['txtLugarExpedicion'],
$_REQUEST['txtFechaExpedicion'],
$_REQUEST['txtTelefono'],
$_REQUEST['txtCiudad'],
$_REQUEST['txtDireccion'],
$_REQUEST['txtCorreoElectronico'],
$_REQUEST['txtParentescoM'],
$_REQUEST['txtNombresCompletosM'],
$_REQUEST['txtPrimerApellidoM'],
$_REQUEST['txtSegundoApellidoM'],
$_REQUEST['txtTipoDocM'],
$_REQUEST['NoDocumentoM'],
$_REQUEST['txtLugarNacimientoM'],
$_REQUEST['txtFechaNacimientoM'],
$_REQUEST['txtLugarExpedicionM'],
$_REQUEST['txtFechaExpedicionM'],
$_REQUEST['txtTelefonoM'],
$_REQUEST['txtCiudadM'],
$_REQUEST['txtDireccionM'],
$_REQUEST['txtCorreoElectronicoM'],
$_REQUEST['txtNivelAcademicoM'],
$_REQUEST['txtProfesionM'],
$_REQUEST['txtTipoTrabajoM'],
$_REQUEST['txtNombreLugarM'],
$_REQUEST['txtCargoM'],
$_REQUEST['txtParentescoP'],
$_REQUEST['txtNombresCompletosP'],
$_REQUEST['txtPrimerApellidoP'],
$_REQUEST['txtSegundoApellidoP'],
$_REQUEST['txtTipoDocP'],
$_REQUEST['NoDocumentoP'],
$_REQUEST['txtLugarNacimientoP'],
$_REQUEST['txtFechaNacimientoP'],
$_REQUEST['txtLugarExpedicionP'],
$_REQUEST['txtFechaExpedicionP'],
$_REQUEST['txtTelefonoP'],
$_REQUEST['txtCiudadP'],
$_REQUEST['txtDireccionP'],
$_REQUEST['txtCorreoElectronicoP'],
$_REQUEST['txtNivelAcademicoP'],
$_REQUEST['txtProfesionP'],
$_REQUEST['txtTipoTrabajoP'],
$_REQUEST['txtNombreLugarP'],
$_REQUEST['txtCargoP'],
$_REQUEST['txtPreguntaUno'],
$_REQUEST['txtPreguntaDos'],
$_REQUEST['txtPreguntaTres']
);

echo json_encode($obj->agregarAspirantes($datos));
